### ISSUE TITLE
Löschen löscht nicht wirklich

### ISSUE THREAD

**Issue by chrismarquardt** [lukasleitsch/Showmator#51]
Ich habe vorhin Live-Shownotes vergeigt und da ich einzelne Einträge nicht löschen konnte (s. letzter Issue), musste ich noch mal von vorne anfangen. Dazu habe ich den "Löschen"-Button gedrückt. Das hat aber die bisherigen Shownotes nicht wirklich gelöscht, d.h. Live-Hörer, die die alte URL benutzt haben, konnten weiterhin meine vergeigten Shownotes sehen.

Ich fände es nett, wenn "Löschen" auch wirklich löschen würde.

**Comment by lukasleitsch** [comment]
In der aktuellen Version haben wir die Benennung überarbeitet. Wenn es weiterhin nicht klar ist, einfach das Issue wieder aufmachen.
